### ISSUE TITLE
Priority can be 0

### ISSUE THREAD

**Issue by amejiarosario** [datastructures-js/priority-queue#11]
https://github.com/datastructures-js/priority-queue/blob/949710495e0bf06259b01f09631fd41e4fb548cf/src/priorityQueue.js#L78

This should be allow:

```js
  const pq = new MinPriorityQueue();
  pq.enqueue(K, 0);
```
It's a common use case. E.g., when implementing Dijkstra's algorithm, the first node's priority is usually set to zero.

**Comment by eyas-ranjous** [comment]
Fixed and released in **v4.1.2** https://github.com/datastructures-js/priority-queue/releases/tag/v4.1.2
