### ISSUE TITLE
Can't use PriorityQueue on Leetcode but MaxPriorityQueue and MinPriorityQueue are working fine

### ISSUE THREAD

**Issue by toantd90** [datastructures-js/priority-queue#35]
Leetcode support `datastructure-js/priority-queue` as the site mentioned [here](https://support.leetcode.com/hc/en-us/articles/360011833974-What-are-the-environments-for-the-programming-languages-).

It is ok if I use `MinPriorityQueue` and `MaxPriorityQueue`, but when I tried to use 

`let tasksQueue = new PriorityQueue({ compare: [customCompare]})`

It say **ReferenceError: PriorityQueue is not defined**.  Import with CommonJS or ESModule doesn't work either. Module is still exporting from [index.js file](https://github.com/datastructures-js/priority-queue/blob/master/index.js), so I'm not sure what the issue is here.

**Comment by eyas-ranjous** [comment]
hi @toantd90 unfortunately, leetcode has not upgraded to latest version. I am also working on a new major version, that will make using this library way easier for everybody. I will talk to leetcode support about it in order to upgrade to it.

**Comment by eyas-ranjous** [comment]
v6 release + leetcode support contacted about it.

**Comment by clalexni** [comment]
probably need a link to the previous readme until leetcode upgraded their environment

**Comment by eyas-ranjous** [comment]
leetcode can do that on their end yes. I cannot see what version is leetcode is using at the moment. If you know, you can go to the release tags, and click on the one they use, and view readme there.

**Comment by apriil15** [comment]
@eyas-ranjous 
Hey, a little question here

Just wonder whether leetcode supports `TS`, if yes maybe what version of this repo I can use?

because I got error like this: `'MinPriorityQueue' refers to a value, but is being used as a type here. Did you mean 'typeof MinPriorityQueue'?`

**Comment by eyas-ranjous** [comment]
No idea why they haven't upgraded yet. I sent a message to support since some time. The are using v4 still. This is the Readme for reference https://github.com/datastructures-js/priority-queue/tree/42e236c0bbd8f7dafc696566823f2ca7968b909d I also asked them to include the library in typescript env as it supports types, they haven't done that yet it seems.

**Comment by apriil15** [comment]
Thanks for your answer~
I'll just use JS for this case haha
Hope LeetCode team will support soon.

**Comment by manoharreddyporeddy** [comment]
A few years ago, I was the one who requested LeetCode, to add support for Heap/PriorityQueue
After few days, they add below support
- https://www.npmjs.com/package/@datastructures-js/queue
- https://www.npmjs.com/package/@datastructures-js/priority-queue   <--- this module we are talking about her
Support added can seen here:
https://support.leetcode.com/hc/en-us/articles/360011833974-What-are-the-environments-for-the-programming-languages-
![image](https://user-images.githubusercontent.com/8236389/224486751-1b5ef46e-6f2a-4576-b611-1392ae6948f3.png)

===

Regarding `PriorityQueue`, LeetCode does support older version

Example usages:

**As of today** `March 2023`, these work fine:

    let pq = new PriorityQueue({   compare: (a, b) => a-b,    });
    let pq = new PriorityQueue({   compare: (a, b) => b-a,    });
    let pq = new PriorityQueue({   compare: (a, b) => b[0] - a[0] || b[1] - a[1],    });    // [v1,v2] element, used today

**In the future, when they upgrade**, below will supported:

    let pq = new PriorityQueue(   (a, b) => a-b      );
    let pq = new PriorityQueue(   (a, b) => b-a      );
    let pq = new PriorityQueue(   (a, b) => b[0] - a[0] || b[1] - a[1]      );

**Comment by eyas-ranjous** [comment]
@manoharreddyporeddy thanks for the details. I hope they upgrade to latest version soon. It has a better interface and some improvements. I also suggested in my last email to support adding the libs to typescript env as all libs have type definitions.
