### ISSUE TITLE
Add remove method

### ISSUE THREAD

**Issue by viniciuscosta110** [datastructures-js/priority-queue#37]
So, I was using this module, and I had to remove an element in the middle of the queue.
I was able to change the value using: priorityQueue.toArray()[j] = newValue
If it had a remove method, this action would be simple.

**Comment by eyas-ranjous** [comment]
Removing from priority queue is donde in priority using dequeue. Can you please share the use case that requires removing an element from it outside of its standard interface?

**Comment by viniciuscosta110** [comment]
So, I was using it as a Frontier for A* algorithm and I had to remove an item in the middle of the Queue because I had to update it with new values. Like in that piece of code:
```
      if (new_f_cost < neigh.f_cost) {
        neigh.parent = current;
        neigh.g_cost = new_g_cost;
        neigh.f_cost = new_f_cost;

        if (frontier.contains(neigh)) {
          frontier.remove(neigh);
        }

        frontier.add(neigh);
      }
```

**Comment by eyas-ranjous** [comment]
this is not a standard use case for a priority queue, you are trying to search and replace a value at certain position. you even need "contains" function, which needs to scan the heap in O(n) already, to find the node position, and then "remove" in O(log(n)). Despite that sounding normal, it is against the priority-based interface. You should remove and re-insert in priority queue if you need to replace a value.

yes there are some things that can be done in the core of the heap, but and at the moment I might hold on adding it, however to your case, I suggest this workaround, 

```js
      if (new_f_cost < neigh.f_cost) {
        const removed = [];
        while (!frontier.isEmpty() && frontier.front().g_cost !== neigh.g_cost) {
          // remove elements until you arrive to the target node
          removed.push(frontier.dequeue());
        }
        // now you have the required node at the front of the queue if exists, remove it
        frontier.dequeue();

        // return the dequeued nodes
        removed.forEach((n) => frontier.enqueue(n));

        // update node
        neigh.parent = current;
        neigh.g_cost = new_g_cost;
        neigh.f_cost = new_f_cost;
        // re-insert node
        frontier.enqueue(neigh);
      }
```

**Comment by viniciuscosta110** [comment]
It makes sense, I forgot about the standart implementation, thank you for your reply.

> this is not a standard use case for a priority queue, you are trying to search and replace a value at certain position. you even need "contains" function, which needs to scan the heap in O(n) already, to find the node position, and then "remove" in O(log(n)). Despite that sounding normal, it is against the priority-based interface. You should remove and re-insert in priority queue if you need to replace a value.
> 
> yes there are some things that can be done in the core of the heap, but and at the moment I might hold on adding it, however to your case, I suggest this workaround,
> 
> ```js
>       if (new_f_cost < neigh.f_cost) {
>         const removed = [];
>         while (!frontier.isEmpty() && frontier.front().g_cost !== neigh.g_cost) {
>           // remove elements until you arrive to the target node
>           removed.push(frontier.dequeue());
>         }
>         // now you have the required node at the front of the queue if exists, remove it
>         frontier.dequeue();
> 
>         // return the dequeued nodes
>         removed.forEach((n) => frontier.enqueue(n));
> 
>         // update node
>         neigh.parent = current;
>         neigh.g_cost = new_g_cost;
>         neigh.f_cost = new_f_cost;
>         // re-insert node
>         frontier.enqueue(neigh);
>       }
> ```
