### ISSUE TITLE
".enqueue expects a numeric priority".

### ISSUE THREAD

**Issue by aadil42** [datastructures-js/priority-queue#53]
I am getting this error ".enqueue expects a numeric priority" when I try to use your library in the Leetcode JS environment.  Can You help me with what's wrong here?

here is my code:

const pq = new MinPriorityQueue((node) => node.val);
 
pq.enqueue({
        val: 5,
        row: 0,
        col: 0
    });

**Comment by eyas-ranjous** [comment]
Leetcode needs to upgrade to latest version of the library.
