### ISSUE TITLE
remove method

### ISSUE THREAD

**Issue by huba888** [datastructures-js/priority-queue#54]
Can you provide a remove method for this library? Normally the priority queue can only remove heap-top elements, but I have encountered non-maximum or minimum elements that need to be removed, and I would like you to provide a remove(element):void method (element in priority), although its time complexity may not be very good

**Comment by eyas-ranjous** [comment]
v6.3.0 released. remove method: https://github.com/datastructures-js/priority-queue#remove

**Comment by huba888** [comment]
Thank you for providing this feature.
