### ISSUE TITLE
How to contribute to v5?

### ISSUE THREAD

**Issue by SevenOutman** [datastructures-js/priority-queue#57]
I'd like to port some features in v6, e.g. `.fromArray()`, back to v5. Which branch should my PR target?

**Comment by eyas-ranjous** [comment]
hi @SevenOutman 

I am not maintaining the prev releases as a branch from the repo, as they lacked essential features and latest is the one that will be maintained. any reason why you need v5 over v6?

**Comment by SevenOutman** [comment]
The main reason is around the API breaking changes in v6

1. I'm using this lib on LeetCode. They don't seem to have a plan to upgrade to v6 and I guess the backward-incompatibility is one of the reasons.
2. I'm in favor of the API signatures in v5, which is, specifying priority for elements per `.enqueue()` call rather than in the constructor.

**Comment by eyas-ranjous** [comment]
@SevenOutman I have forked v5 into its own branch to be maintained for the purpose of leetcode version. https://github.com/datastructures-js/priority-queue/tree/v5 I will update v6 readme to point to this branch for leetcode matters. feel free to add your fixes to the v5, please remember to add updates on readme and tests as well

**Comment by eyas-ranjous** [comment]
I also created a branch for V4 https://github.com/datastructures-js/priority-queue/tree/v4 I see that they are still on v4 on their javascript env https://support.leetcode.com/hc/en-us/articles/360011833974-What-are-the-environments-for-the-programming-languages-

**Comment by SevenOutman** [comment]
> @SevenOutman I have forked v5 into its own branch to be maintained for the purpose of leetcode version. https://github.com/datastructures-js/priority-queue/tree/v5 I will update v6 readme to point to this branch for leetcode matters. feel free to add your fixes to the v5, please remember to add updates on readme and tests as well

Thanks for being open!
